openapi: 3.0.0
info:
  title: trips
  version: 1.0.0
servers:
  - url: localhost://
paths:
  /v2/trips:
    get:
      tags:
        - trips
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    requirements:
                      type: string
                    startDate:
                      type: string
                      format: date
                    endDate:
                      type: string
                      format: date
    post:
      tags:
        - trips
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Title
                description: description
                requirements: reequirements
                startDate: '2023-07-10 15:00:00.000'
                endDate: '2023-07-15 15:00:00.000'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    requirements:
                      type: string
                    startDate:
                      type: string
                      format: date
                    endDate:
                      type: string
                      format: date